/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cameraapp;

/**
 *
 * @author janis_000
 */
public class CameraApp extends javax.swing.JFrame {

    /**
     * Creates new form mainForm
     */
    public CameraApp() {
        initComponents();
    }

    int inputMM = 0;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupCropFactor = new javax.swing.ButtonGroup();
        btnSort = new javax.swing.JButton();
        label35mmEqualOutput = new javax.swing.JLabel();
        textFocalLengthInput = new javax.swing.JTextField();
        label35mmEq = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        labelLensType2 = new javax.swing.JLabel();
        rb16 = new javax.swing.JRadioButton();
        rb15 = new javax.swing.JRadioButton();
        rb13 = new javax.swing.JRadioButton();
        labelLensTypeOutput = new javax.swing.JLabel();
        labelCropFactor = new javax.swing.JLabel();
        labelLensType3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Focal Length Sort & Full Frame Equivalent");
        setResizable(false);

        btnSort.setText("FL Sort");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        label35mmEqualOutput.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        label35mmEqualOutput.setText("None");

        label35mmEq.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        label35mmEq.setText("35mm Equivalent:");

        labelLensType2.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        labelLensType2.setText("Lens Type:");

        buttonGroupCropFactor.add(rb16);
        rb16.setSelected(true);
        rb16.setText("1.6x");

        buttonGroupCropFactor.add(rb15);
        rb15.setText("1.5x");

        buttonGroupCropFactor.add(rb13);
        rb13.setText("1.3x");

        labelLensTypeOutput.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        labelLensTypeOutput.setText("None");

        labelCropFactor.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        labelCropFactor.setText("Crop Factor");

        labelLensType3.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        labelLensType3.setText("Focal Length");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rb13)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(rb16)
                                            .addComponent(rb15))
                                        .addGap(108, 108, 108)
                                        .addComponent(label35mmEq, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(label35mmEqualOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addComponent(labelCropFactor, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelLensType3, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnSort, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addComponent(textFocalLengthInput)))
                .addGap(39, 39, 39)
                .addComponent(labelLensType2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLensTypeOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 318, Short.MAX_VALUE)
                .addGap(83, 83, 83))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(labelLensType3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textFocalLengthInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelLensType2)
                            .addComponent(labelLensTypeOutput))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(btnSort)
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelCropFactor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(label35mmEq)
                        .addComponent(label35mmEqualOutput))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(rb16)
                        .addGap(7, 7, 7)
                        .addComponent(rb15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rb13)))
                .addGap(17, 17, 17))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        
        inputMM = Integer.parseInt(textFocalLengthInput.getText());
        
        if (inputMM > 0 && inputMM <= 24) {
            labelLensTypeOutput.setText("Extreme Wide Angle");
        } else if (inputMM > 24 && inputMM <= 35) {
            labelLensTypeOutput.setText("Wide Angle");
        } else if (inputMM > 35 && inputMM <= 70) {
            labelLensTypeOutput.setText("Normal");
        } else if (inputMM > 70 && inputMM <= 100) {
            labelLensTypeOutput.setText("Medium Telephoto");
        } else if (inputMM > 100 && inputMM <= 300) {
            labelLensTypeOutput.setText("Telephoto");
        } else if (inputMM > 300) {
            labelLensTypeOutput.setText("Super Telephoto");
        } else {
            labelLensTypeOutput.setText("Invalid focal length input!");
        }
        
        double cropFactor = 0;
        double FFeq = 0;
        
        if (rb13.isSelected()) {
            cropFactor = 1.3;
        } else if (rb15.isSelected()) {
            cropFactor = 1.5;
        } else if (rb16.isSelected()) {
            cropFactor = 1.6;
        }
        
        FFeq = inputMM * cropFactor;
        
        label35mmEqualOutput.setText(String.valueOf(FFeq));
        
    }//GEN-LAST:event_btnSortActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CameraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CameraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CameraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CameraApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CameraApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSort;
    private javax.swing.ButtonGroup buttonGroupCropFactor;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel label35mmEq;
    private javax.swing.JLabel label35mmEqualOutput;
    private javax.swing.JLabel labelCropFactor;
    private javax.swing.JLabel labelLensType2;
    private javax.swing.JLabel labelLensType3;
    private javax.swing.JLabel labelLensTypeOutput;
    private javax.swing.JRadioButton rb13;
    private javax.swing.JRadioButton rb15;
    private javax.swing.JRadioButton rb16;
    private javax.swing.JTextField textFocalLengthInput;
    // End of variables declaration//GEN-END:variables
}
